Homework3
IvanPiankov/EPAM_Piankov_Ivan pull request #3
Opened 2021-07-02 09:27 UTC by IvanPiankov

2021-07-04 07:50 UTC, lev-titov requested changes

2021-07-04 07:50 UTC, lev-titov commented on homework3/task2/slow_func/slow_func.py
> +def multiproc_Pool_function():
```suggestion
def multiproc_Pool_function() -> Any:
```

2021-07-04 07:50 UTC, lev-titov commented on homework3/task3/Filter/filter.py
> +                return False
```suggestion
        for key, value in keywords.items():
            if item_of_data.get(key) is not value:
                return False
                
```

2021-07-04 07:50 UTC, lev-titov commented on homework3/task4/arm_num/arm_num.py
> +    return number == result_arm
```suggestion
    return number == sum(list(result_arm_map))
```

2021-07-08 11:52 UTC, IvanPiankov reviewed
File change

2021-07-09 12:29 UTC, lev-titov approved these changes

2021-07-27 13:04 UTC, merged